/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'authorUsername' : string,
  'createdAt' : bigint,
  'text' : string,
  'author' : Principal,
  'imageId' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Image {
  'id' : bigint,
  'title' : string,
  'pending' : boolean,
  'views' : bigint,
  'owner' : Principal,
  'blob' : ExternalBlob,
  'tags' : Array<string>,
  'aspectClass' : string,
  'likes' : bigint,
  'approved' : boolean,
  'downloads' : bigint,
}
export interface PublicUserProfile {
  'bio' : string,
  'username' : string,
  'uploadCount' : bigint,
  'totalLikesReceived' : bigint,
}
export interface User {
  'id' : Principal,
  'bio' : string,
  'username' : string,
  'role' : UserRole,
}
export interface UserProfile { 'bio' : string, 'username' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string], undefined>,
  'addFavorite' : ActorMethod<[bigint], undefined>,
  'approveImage' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteImage' : ActorMethod<[bigint], undefined>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getCallerProfile' : ActorMethod<[], User>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[bigint], Array<Comment>>,
  'getFavorites' : ActorMethod<[], Array<bigint>>,
  'getImage' : ActorMethod<[bigint], Image>,
  'getPendingReview' : ActorMethod<[], Array<Image>>,
  'getPublicGallery' : ActorMethod<[], Array<Image>>,
  'getPublicUserProfile' : ActorMethod<[Principal], [] | [PublicUserProfile]>,
  'getUserImages' : ActorMethod<[Principal], Array<Image>>,
  'getUserLikedImages' : ActorMethod<[], Array<bigint>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'incrementDownloads' : ActorMethod<[bigint], undefined>,
  'incrementViews' : ActorMethod<[bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeImage' : ActorMethod<[bigint], undefined>,
  'registerUser' : ActorMethod<[string, string], undefined>,
  'rejectImage' : ActorMethod<[bigint], undefined>,
  'removeFavorite' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unlikeImage' : ActorMethod<[bigint], undefined>,
  'updateProfile' : ActorMethod<[string, string], undefined>,
  'uploadImage' : ActorMethod<
    [string, Array<string>, string, ExternalBlob],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];