/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AlbumInput = IDL.Record({
  'password' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isPublic' : IDL.Bool,
});
export const Album = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageIds' : IDL.Vec(IDL.Nat),
  'passwordHash' : IDL.Text,
  'isPublic' : IDL.Bool,
});
export const User = IDL.Record({
  'id' : IDL.Principal,
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'role' : UserRole,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'authorUsername' : IDL.Text,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'imageId' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Image = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'pending' : IDL.Bool,
  'views' : IDL.Nat,
  'owner' : IDL.Principal,
  'blob' : ExternalBlob,
  'tags' : IDL.Vec(IDL.Text),
  'aspectClass' : IDL.Text,
  'likes' : IDL.Nat,
  'approved' : IDL.Bool,
  'downloads' : IDL.Nat,
});
export const PublicUserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'uploadCount' : IDL.Nat,
  'totalLikesReceived' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addFavorite' : IDL.Func([IDL.Nat], [], []),
  'addImageToAlbum' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'approveImage' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changeRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAlbum' : IDL.Func([AlbumInput], [IDL.Nat], []),
  'deleteAlbum' : IDL.Func([IDL.Nat], [], []),
  'deleteImage' : IDL.Func([IDL.Nat], [], []),
  'getAlbum' : IDL.Func([IDL.Nat, IDL.Text], [Album], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getCallerProfile' : IDL.Func([], [User], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getImage' : IDL.Func([IDL.Nat], [Image], ['query']),
  'getPendingReview' : IDL.Func([], [IDL.Vec(Image)], ['query']),
  'getPublicAlbums' : IDL.Func([], [IDL.Vec(Album)], ['query']),
  'getPublicGallery' : IDL.Func([], [IDL.Vec(Image)], ['query']),
  'getPublicUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PublicUserProfile)],
      ['query'],
    ),
  'getUserAlbums' : IDL.Func([IDL.Principal], [IDL.Vec(Album)], ['query']),
  'getUserImages' : IDL.Func([IDL.Principal], [IDL.Vec(Image)], ['query']),
  'getUserLikedImages' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'incrementDownloads' : IDL.Func([IDL.Nat], [], []),
  'incrementViews' : IDL.Func([IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeImage' : IDL.Func([IDL.Nat], [], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'rejectImage' : IDL.Func([IDL.Nat], [], []),
  'removeFavorite' : IDL.Func([IDL.Nat], [], []),
  'removeImageFromAlbum' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unlikeImage' : IDL.Func([IDL.Nat], [], []),
  'updateAlbum' : IDL.Func([IDL.Nat, AlbumInput], [], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'uploadImage' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, ExternalBlob],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AlbumInput = IDL.Record({
    'password' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isPublic' : IDL.Bool,
  });
  const Album = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageIds' : IDL.Vec(IDL.Nat),
    'passwordHash' : IDL.Text,
    'isPublic' : IDL.Bool,
  });
  const User = IDL.Record({
    'id' : IDL.Principal,
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'role' : UserRole,
  });
  const UserProfile = IDL.Record({ 'bio' : IDL.Text, 'username' : IDL.Text });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'authorUsername' : IDL.Text,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'imageId' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Image = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'pending' : IDL.Bool,
    'views' : IDL.Nat,
    'owner' : IDL.Principal,
    'blob' : ExternalBlob,
    'tags' : IDL.Vec(IDL.Text),
    'aspectClass' : IDL.Text,
    'likes' : IDL.Nat,
    'approved' : IDL.Bool,
    'downloads' : IDL.Nat,
  });
  const PublicUserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'uploadCount' : IDL.Nat,
    'totalLikesReceived' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addFavorite' : IDL.Func([IDL.Nat], [], []),
    'addImageToAlbum' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'approveImage' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changeRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAlbum' : IDL.Func([AlbumInput], [IDL.Nat], []),
    'deleteAlbum' : IDL.Func([IDL.Nat], [], []),
    'deleteImage' : IDL.Func([IDL.Nat], [], []),
    'getAlbum' : IDL.Func([IDL.Nat, IDL.Text], [Album], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getCallerProfile' : IDL.Func([], [User], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getImage' : IDL.Func([IDL.Nat], [Image], ['query']),
    'getPendingReview' : IDL.Func([], [IDL.Vec(Image)], ['query']),
    'getPublicAlbums' : IDL.Func([], [IDL.Vec(Album)], ['query']),
    'getPublicGallery' : IDL.Func([], [IDL.Vec(Image)], ['query']),
    'getPublicUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PublicUserProfile)],
        ['query'],
      ),
    'getUserAlbums' : IDL.Func([IDL.Principal], [IDL.Vec(Album)], ['query']),
    'getUserImages' : IDL.Func([IDL.Principal], [IDL.Vec(Image)], ['query']),
    'getUserLikedImages' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'incrementDownloads' : IDL.Func([IDL.Nat], [], []),
    'incrementViews' : IDL.Func([IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeImage' : IDL.Func([IDL.Nat], [], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'rejectImage' : IDL.Func([IDL.Nat], [], []),
    'removeFavorite' : IDL.Func([IDL.Nat], [], []),
    'removeImageFromAlbum' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unlikeImage' : IDL.Func([IDL.Nat], [], []),
    'updateAlbum' : IDL.Func([IDL.Nat, AlbumInput], [], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'uploadImage' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, ExternalBlob],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };